extension-components/data-components/data-api/src/main/java/com/milesight/beaveriot/data/filterable/SearchFilter.java
Modify the query conditions of filterable
=> fix: Modify filterable query conditions

extension-components/data-components/data-api/src/main/java/com/milesight/beaveriot/data/filterable/SearchFilter.java
Modify the logical condition of the filterable
=> fix: Modify filterable logic condition

core/rule-engine/rule-engine-components/src/main/java/com/milesight/beaveriot/rule/components/code/ScriptCodeComponent.java, core/rule-engine/rule-engine-components/src/main/resources/camel-schema/choice.json, services/workflow/workflow-service/src/main/java/com/milesight/beaveriot/rule/components/entityassigner/EntityAssignerComponent.java, services/workflow/workflow-service/src/main/java/com/milesight/beaveriot/rule/components/entityselector/EntitySelectorComponent.java, services/workflow/workflow-service/src/main/java/com/milesight/beaveriot/rule/components/eventlistener/EventListenerEndpoint.java, services/workflow/workflow-service/src/main/java/com/milesight/beaveriot/rule/components/serviceinvocation/ServiceInvocationComponent.java, services/workflow/workflow-service/src/main/java/com/milesight/beaveriot/rule/components/webhook/WebhookComponent.java, services/workflow/workflow-service/src/main/resources/camel-schema/trigger.json
=> feat: Modify UI Component config

application/application-standard/src/test/resources/config-schema/sample.json, application/application-standard/src/test/resources/config-schema/sample_choice.json, application/application-standard/src/test/resources/config-schema/sample_choice_choice.json, application/application-standard/src/test/resources/config-schema/sample_choice_complex.json, application/application-standard/src/test/resources/config-schema/sample_eventlistener.json, application/application-standard/src/test/resources/config-schema/sample_parallel.json, core/rule-engine/rule-engine-api/src/main/java/com/milesight/beaveriot/rule/model/flow/config/RuleEdgeConfig.java, core/rule-engine/rule-engine-api/src/main/java/com/milesight/beaveriot/rule/model/flow/config/RuleFlowConfig.java, core/rule-engine/rule-engine-api/src/main/java/com/milesight/beaveriot/rule/model/flow/config/RuleNodeConfig.java, core/rule-engine/rule-engine-api/src/main/java/com/milesight/beaveriot/rule/support/RuleFlowIdGenerator.java, core/rule-engine/rule-engine-core/src/main/java/com/milesight/beaveriot/rule/flow/builder/RuleFlowGraph.java, core/rule-engine/rule-engine-core/src/main/java/com/milesight/beaveriot/rule/flow/builder/RuleFlowYamlBuilder.java
Modify process design structure
=> feat: Modify process design structure

application/application-standard/pom.xml, core/context/src/main/java/com/milesight/beaveriot/context/api/EntityValueServiceProvider.java, core/context/src/main/java/com/milesight/beaveriot/context/integration/wrapper/AbstractWrapper.java, core/context/src/main/java/com/milesight/beaveriot/context/integration/wrapper/AnnotatedEntityWrapper.java, core/context/src/main/java/com/milesight/beaveriot/context/integration/wrapper/AnnotatedTemplateEntityWrapper.java, core/context/src/main/java/com/milesight/beaveriot/context/integration/wrapper/EntityWrapper.java, extension-components/data-components/data-api/src/main/java/com/milesight/beaveriot/data/util/PageConverter.java, services/dashboard/dashboard-service/src/main/java/com/milesight/beaveriot/dashboard/facade/DashboardFacade.java, services/entity/entity-service/src/main/java/com/milesight/beaveriot/entity/service/EntityService.java, services/entity/entity-service/src/main/java/com/milesight/beaveriot/entity/service/EntityValueService.java, services/integration/src/main/java/com/milesight/beaveriot/integration/service/IntegrationService.java, services/user/user-api/src/main/java/com/milesight/beaveriot/user/facade/IUserFacade.java, services/user/user-service/src/main/java/com/milesight/beaveriot/user/facade/UserFacade.java, services/user/user-service/src/main/java/com/milesight/beaveriot/user/service/RoleService.java, services/workflow/workflow-service/src/main/java/com/milesight/beaveriot/rule/components/entityselector/EntitySelectorComponent.java
[Add field filtering for unallocated users and dashboards](https://github.com/Milesight-IoT/beaver-iot/commit/c106d07a9f32e57bdeb2251ae870afd51d28da98)
[refactor: use Object instead of JsonNode in entityValueServiceProvider](https://github.com/Milesight-IoT/beaver-iot/commit/d463699293bbb49f520e3c8964041bd4ca267913)
=> use Object instead of JsonNode and fix page bugs

application/application-standard/src/test/java/com/milesight/beaveriot/sample/entity/DemoIntegrationEntities.java, core/context/src/main/java/com/milesight/beaveriot/context/integration/entity/annotation/AnnotationEntityLoader.java, core/context/src/main/java/com/milesight/beaveriot/context/integration/entity/annotation/Attribute.java, core/context/src/main/java/com/milesight/beaveriot/context/integration/model/AttributeBuilder.java
Adjust required configuration to optional
=> refactor: Adjust required configuration to optional

services/entity/entity-service/src/main/java/com/milesight/beaveriot/entity/service/EntityService.java, services/workflow/workflow-service/src/main/java/com/milesight/beaveriot/rule/components/httpin/HttpInConstants.java, services/workflow/workflow-service/src/main/java/com/milesight/beaveriot/rule/components/httpin/HttpInConsumer.java, services/workflow/workflow-service/src/main/java/com/milesight/beaveriot/rule/components/httpin/HttpInEndpoint.java, services/workflow/workflow-service/src/main/java/com/milesight/beaveriot/rule/components/httpin/HttpInRequestListener.java, services/workflow/workflow-service/src/main/java/com/milesight/beaveriot/rule/components/httpin/model/HttpInRequestContent.java
* Query params / from-data / x-www-form-urlencoded -> params
* raw (json / text / js...) / others -> body
=> feat: add param to http in endpoint

application/application-standard/src/main/resources/application.yml, application/application-standard/src/main/resources/db/h2/sql/v1.2.0/resource.sql, application/application-standard/src/main/resources/db/postgres/sql/v1.2.0/resource.sql, core/context/src/main/java/com/milesight/beaveriot/context/constants/CacheKeyConstants.java, extension-components/resource/src/main/java/com/milesight/beaveriot/resource/adapter/db/service/DbResourceController.java, extension-components/resource/src/main/java/com/milesight/beaveriot/resource/adapter/db/service/DbResourceService.java, services/resource-manager/resource-service/pom.xml, services/resource-manager/resource-service/src/main/java/com/milesight/beaveriot/resource/manager/constants/ResourceManagerConstants.java, services/resource-manager/resource-service/src/main/java/com/milesight/beaveriot/resource/manager/po/ResourceTempPO.java, services/resource-manager/resource-service/src/main/java/com/milesight/beaveriot/resource/manager/service/ResourceService.java
* Add `settled` to resource temp. Clean temp resource every minute. If the resource is not settled, it will be totally deleted.
* Remove db resource from common auth control
=> feat: schedule to clean temp resources

extension-components/resource/src/main/java/com/milesight/beaveriot/resource/config/ResourceConstants.java, services/workflow/workflow-manager/src/main/java/com/milesight/beaveriot/rule/manager/service/WorkflowLogService.java
=> fix: extend filename length and fix delete large size of workflow log in batch

application/application-standard/src/main/resources/db/h2/sql/v1.2.0/entity.sql, application/application-standard/src/main/resources/db/postgres/sql/v1.2.0/entity.sql, core/context/src/main/java/com/milesight/beaveriot/context/api/EntityServiceProvider.java, services/entity/entity-service/src/main/java/com/milesight/beaveriot/entity/service/EntityService.java
Add deleteByKey function for EntityServiceProvider
=> feat: add deleteByKey function for EntityServiceProvider

core/context/src/main/java/com/milesight/beaveriot/context/model/DeviceTemplateModel.java
Serialize the JsonType in the device template as lowercase.
=> chore: Serialize the JsonType in the device template as lowercase

core/context/src/main/java/com/milesight/beaveriot/context/api/DeviceTemplateParserProvider.java, services/device-template/device-template-api/src/main/java/com/milesight/beaveriot/devicetemplate/facade/IDeviceTemplateParserFacade.java, services/device-template/device-template-service/src/main/java/com/milesight/beaveriot/devicetemplate/enums/ServerErrorCode.java, services/device-template/device-template-service/src/main/java/com/milesight/beaveriot/devicetemplate/parser/DeviceTemplateParser.java, services/device-template/device-template-service/src/main/java/com/milesight/beaveriot/devicetemplate/parser/DeviceTemplateParserProviderImpl.java
Add new api 'createDevice' in DeviceTemplateParserProvider
=> feat: add new api 'createDevice' in DeviceTemplateParserProvider

services/device-template/device-template-service/src/main/java/com/milesight/beaveriot/devicetemplate/parser/DeviceTemplateParser.java
Allow Long or Integer value in data type 'Double'.
=> feat: allow Long or Integer value in data type 'Double'

extension-components/metrics/src/main/java/com/milesight/beaveriot/metrics/autoconfigure/MicrometerAutoConfiguration.java
Register TimedAspect and CountedAspect in MicrometerAutoConfiguration to support micrometer aspect
=> feat: support micrometer aspect

core/context/src/main/java/com/milesight/beaveriot/context/api/DeviceServiceProvider.java, services/device-template/device-template-service/src/main/java/com/milesight/beaveriot/devicetemplate/service/DeviceTemplateService.java, services/device/device-service/src/main/java/com/milesight/beaveriot/device/repository/DeviceRepository.java, services/device/device-service/src/main/java/com/milesight/beaveriot/device/service/DeviceServiceProviderImpl.java
Modify: delete related devices when device template deleted
=> feat: delete related devices when device template deleted

core/base/src/main/java/com/milesight/beaveriot/base/enums/EntityErrorCode.java, core/base/src/main/java/com/milesight/beaveriot/base/enums/ErrorCode.java, core/base/src/main/java/com/milesight/beaveriot/base/error/DefaultExceptionHandler.java, core/base/src/main/java/com/milesight/beaveriot/base/error/ErrorHolder.java, core/base/src/main/java/com/milesight/beaveriot/base/error/ErrorHolderExt.java, core/base/src/main/java/com/milesight/beaveriot/base/exception/MultipleErrorException.java, core/base/src/main/java/com/milesight/beaveriot/base/utils/ValidationUtils.java, core/context/src/main/java/com/milesight/beaveriot/context/integration/model/AttributeBuilder.java, core/context/src/main/java/com/milesight/beaveriot/context/integration/model/Entity.java, core/context/src/main/java/com/milesight/beaveriot/context/integration/model/ExchangePayload.java
Feat: Add exchange payload validation via definition of entity
=> feat: add exchange payload validation via definition of entity

core/context/src/main/java/com/milesight/beaveriot/context/integration/model/Entity.java, core/context/src/main/java/com/milesight/beaveriot/context/integration/model/EntityBuilder.java, core/context/src/main/java/com/milesight/beaveriot/context/integration/model/ExchangePayload.java
Fix: Validate children when calling entity 'validate' function
=> fix: validate children when calling entity 'validate' function

services/integration/src/main/java/com/milesight/beaveriot/integration/service/IntegrationServiceProviderImpl.java
Fix: Validate integration entities before saving them
=> fix: validate integration entities before saving them

core/context/src/main/java/com/milesight/beaveriot/context/model/DeviceTemplateModel.java, services/device-template/device-template-service/src/main/java/com/milesight/beaveriot/devicetemplate/parser/DeviceTemplateParser.java, services/device-template/device-template-service/src/main/resources/template/default_device_template.yaml, services/device-template/device-template-service/src/main/resources/template/device_template_schema.json
1. Supports custom device id and device name fields in input definition
2. Optimize device template schema
=> feat: supports custom device id and device name fields in input definition

services/entity/entity-service/src/main/java/com/milesight/beaveriot/entity/service/EntityService.java
Fix: Save entity when 'visible' or 'description' has been changed
=> fix: save entity when 'visible' or 'description' has been changed

core/context/src/main/java/com/milesight/beaveriot/context/integration/model/ExchangePayload.java
Modify: Optimize the logic of the 'getAllChildrenEntities' method
=> chore: optimize the logic of the 'getAllChildrenEntities' method

core/context/src/main/java/com/milesight/beaveriot/context/integration/model/AttributeBuilder.java, core/context/src/main/java/com/milesight/beaveriot/context/integration/model/Entity.java
Feat: Add a mixed mode to the 'IMAGE' entity format that supports both URL and Base64
=> feat: add a mixed mode to the 'IMAGE' entity format

services/device/device-service/src/main/java/com/milesight/beaveriot/device/service/DeviceService.java, services/device/device-service/src/main/java/com/milesight/beaveriot/device/service/DeviceServiceProviderImpl.java
Transaction issue has been fixed in https://github.com/Milesight-IoT/beaver-iot-integrations/pull/72
So the temporary fixing way in #303 should be rollbacked.
=> fix: add back transaction

services/entity/entity-service/src/main/java/com/milesight/beaveriot/entity/service/EntityService.java
Fix: Cover entities when attach target or attach target id changed
=> fix: cover entities when attach target or attach target id changed

services/device-template/device-template-service/src/main/java/com/milesight/beaveriot/devicetemplate/parser/DeviceTemplateParser.java, services/device-template/device-template-service/src/main/resources/i18n/messages.properties, services/device-template/device-template-service/src/main/resources/i18n/messages_en.properties, services/device-template/device-template-service/src/main/resources/i18n/messages_zh_CN.properties, services/device-template/pom.xml
Feat: Add i18n support for device template validation
=> feat: add i18n support for device template validation

core/context/src/main/java/com/milesight/beaveriot/context/api/DeviceStatusServiceProvider.java, services/device/device-service/pom.xml, services/device/device-service/src/main/java/com/milesight/beaveriot/device/repository/DeviceRepository.java, services/device/device-service/src/main/java/com/milesight/beaveriot/device/service/DeviceServiceProviderImpl.java, services/device/device-service/src/main/java/com/milesight/beaveriot/device/status/AbstractDeviceStatusManager.java, services/device/device-service/src/main/java/com/milesight/beaveriot/device/status/BaseDeviceStatusManager.java, services/device/device-service/src/main/java/com/milesight/beaveriot/device/status/DeviceStatusManager.java, services/device/device-service/src/main/java/com/milesight/beaveriot/device/status/autoconfigure/DeviceStatusManagerAutoConfiguration.java, services/device/device-service/src/main/java/com/milesight/beaveriot/device/status/local/DeviceStatusLocalManager.java, services/device/device-service/src/main/java/com/milesight/beaveriot/device/status/redis/DeviceStatusRedisManager.java, services/device/device-service/src/main/java/com/milesight/beaveriot/device/status/service/DeviceStatusService.java
New feature: Introduce the device status manager to take over the status of devices of integrations, supporting both standalone and cluster modes.
=> feat: device status manager

core/context/src/main/java/com/milesight/beaveriot/context/api/DeviceStatusServiceProvider.java, services/device-template/device-template-service/src/main/java/com/milesight/beaveriot/devicetemplate/parser/DeviceTemplateParser.java, services/device/device-service/src/main/java/com/milesight/beaveriot/device/service/DeviceService.java, services/device/device-service/src/main/java/com/milesight/beaveriot/device/status/BaseDeviceStatusManager.java, services/device/device-service/src/main/java/com/milesight/beaveriot/device/status/DeviceStatusManager.java, services/device/device-service/src/main/java/com/milesight/beaveriot/device/status/autoconfigure/DeviceStatusManagerAutoConfiguration.java, services/device/device-service/src/main/java/com/milesight/beaveriot/device/status/local/DeviceStatusLocalManager.java, services/device/device-service/src/main/java/com/milesight/beaveriot/device/status/redis/DeviceStatusRedisManager.java, services/device/device-service/src/main/java/com/milesight/beaveriot/device/status/service/DeviceStatusService.java, services/device/device-service/src/main/java/com/milesight/beaveriot/device/status/service/DeviceStatusServiceProviderImpl.java
=> refactor: optimize device related codes

core/context/src/main/java/com/milesight/beaveriot/context/api/DeviceTemplateServiceProvider.java, services/device-template/device-template-api/src/main/java/com/milesight/beaveriot/devicetemplate/facade/IDeviceTemplateFacade.java, services/device-template/device-template-service/src/main/java/com/milesight/beaveriot/devicetemplate/service/DeviceTemplateService.java, services/device-template/device-template-service/src/main/java/com/milesight/beaveriot/devicetemplate/service/DeviceTemplateServiceProviderImpl.java
Added query APIs for custom device templates in Device Template, to be used by MQTT device integration.
=> feat: new device template query api for mqtt device integration

services/device/device-api/src/main/java/com/milesight/beaveriot/device/facade/IDeviceBlueprintMappingFacade.java, services/device/device-service/src/main/java/com/milesight/beaveriot/device/repository/DeviceBlueprintMappingRepository.java, services/device/device-service/src/main/java/com/milesight/beaveriot/device/service/DeviceBlueprintMappingService.java
feat: New api for device blueprint mapping facade
=> feat: new api for device blueprint mapping facade

core/context/src/main/java/com/milesight/beaveriot/context/api/DeviceStatusServiceProvider.java, services/device/device-service/src/main/java/com/milesight/beaveriot/device/status/BaseDeviceStatusManager.java, services/device/device-service/src/main/java/com/milesight/beaveriot/device/status/DeviceStatusManager.java, services/device/device-service/src/main/java/com/milesight/beaveriot/device/status/constants/DeviceStatusConstants.java, services/device/device-service/src/main/java/com/milesight/beaveriot/device/status/service/DeviceStatusService.java, services/device/device-service/src/main/java/com/milesight/beaveriot/device/status/service/DeviceStatusServiceProviderImpl.java, services/entity-template/entity-template-service/src/main/resources/entity-template.yml
Feature: Introducing a new api `status` in device status manager
=> feat: new api of device status manager

application/application-standard/src/main/resources/application.yml, application/application-standard/src/main/resources/db/h2/sql/v1.3.0/blueprint_library.sql, application/application-standard/src/main/resources/db/postgres/sql/v1.3.0/blueprint_library.sql, core/context/src/main/java/com/milesight/beaveriot/context/integration/bootstrap/IntegrationBootstrapManager.java, core/context/src/main/java/com/milesight/beaveriot/context/model/BlueprintLibrary.java, core/context/src/main/java/com/milesight/beaveriot/context/model/BlueprintLibrarySourceType.java, services/authentication/authentication-service/src/main/java/com/milesight/beaveriot/authentication/config/WebSecurityConfiguration.java, services/blueprint/blueprint-service/src/main/java/com/milesight/beaveriot/blueprint/library/component/BlueprintLibrarySyncScheduler.java, services/blueprint/blueprint-service/src/main/java/com/milesight/beaveriot/blueprint/library/component/BlueprintLibrarySyncer.java, services/blueprint/blueprint-service/src/main/java/com/milesight/beaveriot/blueprint/library/config/BlueprintLibraryConfig.java, services/blueprint/blueprint-service/src/main/java/com/milesight/beaveriot/blueprint/library/controller/BlueprintLibrarySettingController.java, services/blueprint/blueprint-service/src/main/java/com/milesight/beaveriot/blueprint/library/model/BlueprintLibraryAddress.java, services/blueprint/blueprint-service/src/main/java/com/milesight/beaveriot/blueprint/library/po/BlueprintLibraryPO.java, services/blueprint/blueprint-service/src/main/java/com/milesight/beaveriot/blueprint/library/service/BlueprintLibraryAddressService.java, services/blueprint/blueprint-service/src/main/java/com/milesight/beaveriot/blueprint/library/service/BlueprintLibraryService.java, services/user/user-service/src/main/java/com/milesight/beaveriot/user/service/IntegrationAuthorizedService.java
Remove blueprint library environment variables because they are unnecessary
=> chore: remove blueprint library environment variables

core/context/src/main/java/com/milesight/beaveriot/context/model/DeviceTemplateModel.java, services/device-template/device-template-service/src/main/java/com/milesight/beaveriot/devicetemplate/parser/DeviceTemplateParser.java
Fix: Allow null value for type when it is `device_id`
=> fix: allow value null when type is device_id

services/blueprint/blueprint-service/src/main/java/com/milesight/beaveriot/blueprint/library/component/BlueprintLibrarySyncer.java, services/blueprint/blueprint-service/src/main/java/com/milesight/beaveriot/blueprint/library/controller/BlueprintLibrarySettingController.java, services/blueprint/blueprint-service/src/main/java/com/milesight/beaveriot/blueprint/library/model/BlueprintLibrarySubscription.java, services/blueprint/blueprint-service/src/main/java/com/milesight/beaveriot/blueprint/library/repository/BlueprintLibrarySubscriptionRepository.java, services/blueprint/blueprint-service/src/main/java/com/milesight/beaveriot/blueprint/library/service/BlueprintLibrarySubscriptionService.java
Fix: Notify all tenants subscribed to the blueprint library after sync, and ensure tenant context is properly set when invoking listeners
Added: Permission notification in the blueprint settings API
=> fix: some issues about blueprint library

extension-components/resource/src/main/java/com/milesight/beaveriot/resource/ResourceStorage.java, services/blueprint/blueprint-service/src/main/java/com/milesight/beaveriot/blueprint/library/component/BlueprintLibraryResourceResolver.java, services/blueprint/blueprint-service/src/main/java/com/milesight/beaveriot/blueprint/library/component/BlueprintLibrarySyncer.java, services/blueprint/blueprint-service/src/main/java/com/milesight/beaveriot/blueprint/library/controller/BlueprintLibrarySettingController.java, services/blueprint/blueprint-service/src/main/java/com/milesight/beaveriot/blueprint/library/model/BlueprintLibraryZipAddress.java, services/blueprint/blueprint-service/src/main/java/com/milesight/beaveriot/blueprint/library/model/response/QueryBlueprintLibrarySettingResponse.java, services/blueprint/blueprint-service/src/main/java/com/milesight/beaveriot/blueprint/library/service/BlueprintLibraryAddressService.java, services/resource-manager/resource-api/src/main/java/com/milesight/beaveriot/resource/manager/facade/ResourceManagerFacade.java, services/resource-manager/resource-service/src/main/java/com/milesight/beaveriot/resource/manager/service/ResourceService.java
Fix the logic of switching default blueprint library
=> fix: the logic of switching default blueprint library

services/device-template/device-template-service/src/main/java/com/milesight/beaveriot/devicetemplate/parser/DeviceTemplateParser.java
Fix: Throw exception when decoding data error
=> fix: throw exception when decoding data error

services/blueprint/blueprint-service/src/main/java/com/milesight/beaveriot/blueprint/library/component/BlueprintLibrarySyncer.java, services/blueprint/blueprint-service/src/main/java/com/milesight/beaveriot/blueprint/library/service/BlueprintLibraryAddressService.java, services/blueprint/blueprint-service/src/main/java/com/milesight/beaveriot/blueprint/library/support/ZipInputStreamScanner.java
Refactor and optimize codes related to blueprint library sync
=> optimize: blueprint library sync

services/device-template/device-template-service/src/main/java/com/milesight/beaveriot/devicetemplate/parser/DeviceTemplateParser.java, services/permission/permission-service/src/main/java/com/milesight/beaveriot/permission/aspect/DataPermissionAspect.java, services/permission/permission-service/src/main/java/com/milesight/beaveriot/permission/aspect/JpaRepositoryAspect.java, services/permission/permission-service/src/main/java/com/milesight/beaveriot/permission/aspect/TenantAspect.java, services/permission/permission-service/src/main/java/com/milesight/beaveriot/permission/support/ProceedingJoinPointSupport.java
Fix the issue of losing tenant context when saving an entity
=> fix: the issue of losing tenant context when saving an entity
